// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjbgwyvehpvooymldmms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqYmd3eXZlaHB2b295bWxkbW1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODY4MDQsImV4cCI6MjA2NjQ2MjgwNH0.ZSjdY4AlmsvTkCVrNTcNYtOai2NWOAUOQe5zyVioQv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});